### ISSUE TITLE
Namen finden

### ISSUE THREAD

**Issue by openscript** [openscript/myipa#1]
Es geht darum Hilfen, Vorlagen, Tipps und weitere Informationen bzgl. Informatik IPAs zu bieten.
Was könnte ein passender Name sein?

Bitte auch prüfen, ob eine passende Domain noch frei wäre.

**Comment by pwndev** [comment]
Ich finde MyIPA wäre ein guter Name.

Die Domain myipa.ch oder myipa.info würde recht gut passen und ist auch frei.

**Comment by openscript** [comment]
Diesen Namen mag ich auch, weil er kurz und aussagekräftig ist.
